Release 1.0.0
nf-core/rangeland pull request #7
Opened 2024-07-31 18:50 UTC by Felix-Kummer

## PR description
This is the first release of rangeland, a remote sensing pipeline for trend analysis in grasslands.
Rangeland is the first remote sensing pipeline in nf-core and, thus, deviates from most nf-core pipelines.  

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2024-08-05 08:46 UTC, mashehu requested changes
see https://github.com/nf-core/rangeland/pull/8#pullrequestreview-2218166023

2024-08-05 10:28 UTC, nictru commented
Added my thoughts [#8(review](https://github.com/nf-core/rangeland/pull/8#pullrequestreview-2218520137)

2024-11-26 15:16 UTC, mashehu approved these changes

2024-12-16 14:31 UTC, jfy133 approved these changes

2025-01-06 09:22 UTC, jfy133 commented on workflows/rangeland.nf
> +        error "No directories found!"
I would maybe make this more informative.

```suggestion
        error "[nf-core/rangeland] ERROR: No directories found in input tar file!"
```

Or similar

2025-01-06 09:24 UTC, jfy133 commented
My approval still stands!

2025-01-17 11:14 UTC, merged